name: standard
parameters:
  attack:
    type: random choice
    choices: [0, 0.25, 0.5, 0.5, 0.75, 0.75, 1, 1]
  filterFrequency:
    type: range
    min: 200
    max: 16000
  duration:
    type: named random choice
    choices:
      small:
        - 0.0.120
        - 0.0.240
        - 0.0.240
        - 0.0.240
      medium:
        - 0.1.0
        - 0.2.0
      large:
        - 1.0.0
        - 1.2.0
        - 2.0.0
  velocity:
    type: pattern
    choices: [100, 60, 60, 80, 60, 60, 100, 40]
  minMelodyIterations: 20
  minChordIterations: 4
  melodyDurationSize:
    type: random choice
    choices:
      - small
      - small
      - small
      - medium
  chordDurationSize:
    type: random choice
    choices:
      - medium
      - medium
      - medium
      - large
      - large
  melodyStartDegree:
    type: random choice
    choices: [1, 1, 5, [2, 3, 4, 6, 7]]
  chordStartRoot:
    type: random choice
    choices: [1, 1, 5, 5, 3]
  chordStartQuality:
    type: random choice
    choices:
      - type: triad
      - type: triad
      - type: triad
      - type: triad
      - type: dyad
        interval: 8
      - type: dyad
        interval: 3
      - type: dyad
        interval: 4
      - type: dyad
        interval: 5
      - type: dyad
        interval: 6
      - type: dyad
        interval: 7
  melodyNoteDistance:
    type: named random choice
    choices:
      small:
        - small
        - small
        - medium
        - large
        - large
      medium:
        - small
        - medium
      large:
        - small
        - medium
        - medium
        - medium
  chord:
    type: named random choice
    choices:
      dim:
        - type: triad
          degreeOffset: 2
      M:
        - type: triad
          degreeOffset: -2
      m:
        - type: dyad
          interval: 4
          degreeOffset: 0
        - type: dyad
          interval: 6
          degreeOffset: 0
      default:
        - type: triad
        - type: triad
        - type: triad
        - type: triad
        - type: dyad
          interval: 8
        - type: dyad
          interval: 3
        - type: dyad
          interval: 4
        - type: dyad
          interval: 5
        - type: dyad
          interval: 6
        - type: dyad
          interval: 7
