name: Rhythm
description: Manage the sequencer rhythm steps for the active track. Turn steps on and manage sequence step lengths.
rows:
  -
    name: Rhythm Pattern / Step Length
    description: Turn rhythm gate steps on/off; when shift key is on, sets the rhythm step length
    group: rhythm-pattern
    type: toggle / meter
    index: 0
    xStart: 0
    xLength: 16
    mapping: updateRhythm
    shiftMapping: updateStepLength
  -
    name: Rhythm Parameter Row
    description: Set parameter values for the current algorithm
    type: mixed
    index: 4
    xStart: 0
    xLength: 16
    mapping: updateRhythmParameter
    shiftMapping: updateAlternateRhythmParameter
  -
    name: Rhythm Algorithms
    description: Set the current rhythm algorithm
    group: rhythm-algorithm
    type: radio
    index: 6
    xStart: 0
    xLength: 8
    mapping: updateRhythmAlgorithm
    values:
      - manual
      - surround
      - accelerating
      - undefined
      - undefined
      - undefined
      - undefined
      - undefined
  -
    name: Related Track
    description: Set the current track's related rhythm track
    group: related-rhythm
    type: radio
    index: 5
    xStart: 0
    xLength: 7
    mapping: updateRelatedRhythmTrack
  -
    name: Pulse Rate
    description: Set the current track's pulse rate between 16n and 2n
    group: pulse-rate
    type: radio
    index: 5
    xStart: 8
    xLength: 4
    mapping: updatePulse
    values:
      - 16n
      - 8n
      - 4n
      - 2n
  -
    name: Note Length
    description: Set the length of sequencer notes
    group: note-length
    type: meter
    index: 6
    xStart: 8
    xLength: 8
    mapping: updateNoteLength
    values:
      - 16n
      - 8n
      - 8nd
      - 4n
      - 4nd
      - 2n
      - 2nd
      - 1n
