name: Self-similarity Algorithms
description: "Configure the self-similarity algorithms: self-replicating, counted, zig-zag"
matrices:
  -
    name: Rhythm Pattern / Step Length
    description: Turn rhythm gate steps on/off; when shift key is on, sets the rhythm step length
    group: rhythm-pattern
    type: toggle / meter
    rowStart: 0
    rowEnd: 1
    columnStart: 0
    columnEnd: 15
    mapping: updateRhythm
    shiftMapping: updateStepLength
  -
    name: Keyboard Octave
    description: Button represents a note; first button in the row is the current scale's tonic for the row's octave
    group: notes
    type: momentary
    rowStart: 2
    rowEnd: 5
    columnStart: 0
    columnEnd: 14
    mapping: addNotes
    columnValues:
      - 4
      - 3
      - 2
      - 1
rows:
  -
    name: Rhythm Repetitions
    description: Set the number of times thru the gate pattern before switching to the next seed
    group: rhythm-repetition
    type: meter
    index: 2
    xStart: 8
    xLength: 8
    mapping: setRhythmRepetitions
  -
    name: Algorithms
    description: select the current algorithm
    group: algorithms
    type: radio
    index: 6
    xStart: 0
    xLength: 4
    mapping: setAlgorithm
    values:
      - simple
      - shift_reg
      - inf_series
      - self_similarity
  -
    name: Algorithm types
    description: Select whether to use the self-replicating, counted or zig-zag algorithms
    group: self-similarity-type
    type: radio
    index: 6
    xStart: 8
    xLength: 3
    mapping: setSelfSimilaryType
    values:
      - self_replicate
      - counted
      - zig_zag
  -
    name: Advance
    description: advance the current algorithm 1 iteration
    group: advance
    type: momentary
    index: 6
    xStart: 15
    xLength: 1
    mapping: advance
