name: Probabilities
description: Probabilities are accessed on Rhythm page 2. Set per step probabilities for each rhythmic gate.
matrices:
  -
    name: Step Probability
    description: Set the probability for the x-position rhythm step
    group: probability
    type: vertical meter
    rowStart: 0
    rowEnd: 6
    columnStart: 0
    columnEnd: 15
    mapping: updateProbability
    columnValues:
      - 1
      - 0.875
      - 0.75
      - 0.625
      - 0.5
      - 0.375
      - 0.25
    columnDisplayValues:
      - 100%
      - 87.5%
      - 75%
      - 62.5%
      - 50%
      - 37.5%
      - 25%
