name: Mutation
rows:
  -
    name: Participating Voices
    description: Select the voices participating in mutation
    group: mutation-voices
    type: toggle
    index: 0
    xStart: 0
    xLength: 6
    mapping: toggleImprovisingVoice
    values:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
  -
    name: Mutation Algorithms
    description: Select the mutation algorithms used in mutation
    group: mutation-algorithms
    type: toggle
    index: 0
    xStart: 6
    xLength: 8
    mapping: toggleMutationAlgorithm
    values:
      - trps-2
      - rev
      - rot-3
      - sort
      - -sort
      - inv
      - inv-rev
      - bitflip
  -
    name: Queue Mutation Start
    description: Press to start mutation on the start of the next super measure
    group: mutation-controls
    type: momentary
    index: 0
    xStart: 15
    xLength: 1
    mapping: queueMutationStart
  -
    name: Queue Mutation Stop
    description: Press to stop mutation on the start of the next super measure
    group: mutation-controls
    type: momentary
    index: 1
    xStart: 15
    xLength: 1
    mapping: queueMutationStop
  -
    name: Enable Voice Trading
    description: When on, mutating voices will take turns for the length of each super measure
    group: mutation-controls
    type: toggle
    index: 2
    xStart: 15
    xLength: 1
    mapping: toggleVoiceTrading
