name: Chords
description: Add chord progressions to the active track.
matrices:
  -
    name: Keyboard Octave
    description: Button represents a chord note; first button in the row is the current scale's tonic for the row's octave
    group: chord-notes
    type: momentary
    rowStart: 0
    rowEnd: 6
    columnStart: 0
    columnEnd: 14
    mapping: addChordNote
    columnValues:
      - 6
      - 5
      - 4
      - 3
      - 2
      - 1
      - 0
rows:
  -
    name: Toggle Chord Recording
    description: Turn chord recording on/off; when turning on, the queued chord progression clears
    group: note-input-controls
    index: 0
    xStart: 15
    xLength: 1
    type: toggle
    mapping: toggleChordRecording
  -
    name: Remove Last Chord
    description: Remove the last chord from the currently queued chord progression
    group: note-input-controls
    index: 1
    xStart: 15
    xLength: 1
    type: momentary
    mapping: removeLastChord
  -
    name: Toggle Vector Shifts
    description: When on, after processing by the melody algorithm, it will be processed by the melodic vector shifts
    group: melody-recording-controls
    type: toggle
    index: 4
    xStart: 15
    xLength: 1
    mapping: toggleVectorShifts
  -
    name: Toggle Create Clip Mode
    description: When on, will add the chord progression to the next clip
    group: note-input-controls
    index: 5
    xStart: 15
    xLength: 1
    type: toggle
    mapping: toggleNewClipCreation
  -
    name: Add Progression to Track
    description: Adds the currently queued chord progression to the currently selected track
    group: note-input-controls
    index: 6
    xStart: 15
    xLength: 1
    type: momentary
    mapping: setTrackChordProgression
