rows:
  -
    name: 100% Probability
    index: 0
    xStart: 0
    xLength: 16
    type: vertical meter
    value: 1
    mapping: updateProbability
    shiftMapping: updateTrackProbability
  -
    name: 87.5% Probability
    index: 1
    xStart: 0
    xLength: 16
    type: vertical meter
    value: 0.875
    mapping: updateProbability
    shiftMapping: updateTrackProbability

  -
    name: 75% Probability
    index: 2
    xStart: 0
    xLength: 16
    type: vertical meter
    value: 0.75
    mapping: updateProbability
    shiftMapping: updateTrackProbability
  -
    name: 62.5% Probability
    index: 3
    xStart: 0
    xLength: 16
    type: vertical meter
    value: 0.625
    mapping: updateProbability
    shiftMapping: updateTrackProbability
  -
    name: 50% Probability
    index: 4
    xStart: 0
    xLength: 16
    type: vertical meter
    value: 0.5
    mapping: updateProbability
    shiftMapping: updateTrackProbability
  -
    name: 37.5% Probability
    index: 5
    xStart: 0
    xLength: 16
    type: vertical meter
    value: 0.375
    mapping: updateProbability
    shiftMapping: updateTrackProbability
  -
    name: 25% Probability
    index: 6
    xStart: 0
    xLength: 16
    type: vertical meter
    value: 0.25
    mapping: updateProbability
    shiftMapping: updateTrackProbability
