name: Infinity Series Algorithm
description: Configure the infinity series algorithm
rows:
  -
    name: Algorithms
    description: select the current algorithm
    group: algorithms
    type: radio
    index: 6
    xStart: 0
    xLength: 16
    mapping: setAlgorithm
    values:
      - simple
      - shift_reg
      - inf_series
