name: Melody
rows:
  -
    name: Keyboard Octave 6
    description: Button represents a melody note; first button in the row is the current scale's tonic starting at MIDI octave 6
    group: melody-notes
    sub_group: octave-6
    index: 0
    xStart: 0
    xLength: 12
    type: momentary
    mapping: addNote
  -
    name: Keyboard Octave 5
    description: Button represents a melody note; first button in the row is the current scale's tonic starting at MIDI octave 5
    group: melody-notes
    sub_group: octave-5
    index: 1
    xStart: 0
    xLength: 12
    type: momentary
    mapping: addNote
  -
    name: Keyboard Octave 4
    description: Button represents a melody note; first button in the row is the current scale's tonic starting at MIDI octave 4
    group: melody-notes
    sub_group: octave-4
    index: 2
    xStart: 0
    xLength: 12
    type: momentary
    mapping: addNote
  -
    name: Keyboard Octave 3
    description: Button represents a melody note; first button in the row is the current scale's tonic starting at MIDI octave 3
    group: melody-notes
    sub_group: octave-3
    index: 3
    xStart: 0
    xLength: 12
    type: momentary
    mapping: addNote
  -
    name: Keyboard Octave 2
    description: Button represents a melody note; first button in the row is the current scale's tonic starting at MIDI octave 2
    group: melody-notes
    sub_group: octave-2
    index: 4
    xStart: 0
    xLength: 12
    type: momentary
    mapping: addNote
  -
    name: Keyboard Octave 1
    description: Button represents a melody note; first button in the row is the current scale's tonic starting at MIDI octave 1
    group: melody-notes
    sub_group: octave-1
    index: 5
    xStart: 0
    xLength: 12
    type: momentary
    mapping: addNote
  -
    name: Keyboard Octave 0
    description: Button represents a melody note; first button in the row is the current scale's tonic starting at MIDI octave 0
    group: melody-notes
    sub_group: octave-0
    index: 6
    xStart: 0
    xLength: 12
    type: momentary
    mapping: addNote
  -
    name: Scale/Tonic Selection (1/3)
    description: Set the global scale or tonic; tonic is set when the shift key is on
    group: scale-tonic
    index: 0
    xStart: 12
    xLength: 4
    type: radio
    mapping: setScale
    values:
      - 0
      - 1
      - 2
      - 3
  -
    name: Scale/Tonic Selection (2/3)
    description: Set the global scale or tonic; tonic is set when the shift key is on
    group: scale-tonic
    index: 1
    xStart: 12
    xLength: 4
    type: radio
    mapping: setScale
    values:
      - 4
      - 5
      - 6
      - 7
  -
    name: Scale/Tonic Selection (3/3)
    description: Set the global scale or tonic; tonic is set when the shift key is on
    group: scale-tonic
    index: 2
    xStart: 12
    xLength: 4
    type: radio
    mapping: setScale
    values:
      - 8
      - 9
      - 10
      - 11
  -
    name: Toggle Input Melody Recording
    description: Turn melody recording on/off; when turning on, the queued melody progression clears
    group: melody-recording-controls
    type: toggle
    index: 3
    xStart: 12
    xLength: 1
    mapping: toggleMelodyRecording
  -
    name: Remove Last Input Melody Note
    description: Remove the last note from the currently queued melody
    group: melody-recording-controls
    type: momentary
    index: 3
    xStart: 13
    xLength: 1
    mapping: removeLastNote
  -
    name: Toggle Create Clip Mode
    description: When on, will add the melody to the next clip
    group: melody-recording-controls
    type: toggle
    index: 3
    xStart: 14
    xLength: 1
    mapping: toggleNewClipCreation
  -
    name: Melody Algorithms
    description: Generates algorithmic melody for currently selected track
    group: melody-algorithms
    type: momentary
    index: 4
    xStart: 12
    xLength: 4
    mapping: generateMelody
    values:
      - simple
      - self_replicate
      - counted
      - zig_zag
scales:
  -
    name: Major
    mode: Ionian
  -
    name: Minor
    mode: Aeolian
  -
    name: Dorian
  -
    name: Phrygian
  -
    name: Lydian
  -
    name: Mixolydian
  -
    name: Locrian
  -
    name: MajPentatonic
  -
    name: MinPentatonic
  -
    name: WholeTone
  -
    name: GS
  -
    name: Chromatic
modifiers:
  - 0
  - 1
