name: Infinity Series Algorithm
description: Configure the infinity series algorithm
matrices:
  -
    name: Rhythm Pattern / Step Length
    description: Turn rhythm gate steps on/off; when shift key is on, sets the rhythm step length
    group: rhythm-pattern
    type: toggle / meter
    rowStart: 0
    rowEnd: 1
    columnStart: 0
    columnEnd: 15
    mapping: updateRhythm
    shiftMapping: updateStepLength
  -
    name: Seeds
    description: Four rows of infinity series seeds
    group: infinity-seeds
    type: row-meters
    rowStart: 2
    rowEnd: 5
    columnStart: 0
    columnEnd: 7
    mapping: addSeedRange
  -
    name: Active Clip Scene
    description: Button represents the active Ableton Live scene
    group: clip-scenes
    type: toggle
    rowStart: 2
    rowEnd: 5
    columnStart: 14
    columnEnd: 14
    mapping: setClip
    columnValues:
      - 0
      - 1
      - 2
      - 3
rows:
  -
    name: Rhythm Repetitions
    description: Set the number of times thru the gate pattern before switching to the next seed
    group: rhythm-repetition
    type: meter
    index: 2
    xStart: 8
    xLength: 8
    mapping: setRhythmRepetitions
  -
    name: Algorithms
    description: select the current algorithm
    group: algorithms
    type: radio
    index: 6
    xStart: 0
    xLength: 4
    mapping: setAlgorithm
    values:
      - simple
      - inf_series
      - shift_reg
      - self_similarity
  -
    name: Advance
    description: advance the current algorithm 1 iteration
    group: advance
    type: momentary
    index: 6
    xStart: 15
    xLength: 1
    mapping: advance
