name: Global
description: Manage global properties like the super measure length, scale and tonic.
rows:
  -
    name: Super Measure Length
    description: Set the super measure length between 1 and 8 measures
    group: super-measure
    index: 0
    xStart: 0
    xLength: 8
    type: meter
    mapping: updateSuperMeasure
    values:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
matrices:
  -
    name: Scale/Tonic
    description: Set the global scale or tonic; tonic is set when the shift key is on
    group: scale-tonic
    type: radio
    rowStart: 0
    rowEnd: 2
    columnStart: 12
    columnEnd: 15
    mapping: setScaleOrTonic
    rowValues:
      -
        - Major
        - Minor
        - Dorian
        - Phrygian
      -
        - Lydian
        - Mixolydian
        - Locrian
        - MajPentatonic
      -
        - MinPentatonic
        - WholeTone
        - GS
        - Chromatic
    rowShiftValues:
      -
        - 0
        - 1
        - 2
        - 3
      -
        - 4
        - 5
        - 6
        - 7
      -
        - 8
        - 9
        - 10
        - 11
    rowShiftDisplayValues:
      -
        - C
        - C#
        - D
        - D#
      -
        - E
        - F
        - F#
        - G
      -
        - G#
        - A
        - A#
        - B
