name: Global
rows:
  -
    name: Super Measure Length
    description: Set the super measure length between 1 and 8 measures
    group: super-measure
    index: 0
    xStart: 0
    xLength: 8
    type: meter
    mapping: updateSuperMeasure
    values:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
