name: Fills
description: Fills are accessed on Rhythm page 3. Set per step fills for each rhythmic gate.
matrices:
  -
    name: Set Step Fill
    description: Set the number of repeat notes for the x-position rhythm step
    group: fill
    type: vertical meter
    rowStart: 0
    rowEnd: 5
    columnStart: 0
    columnEnd: 15
    mapping: setFillRepeats
    columnValues:
      - 8
      - 6
      - 5
      - 4
      - 3
      - 2
rows:
  -
    name: Display Rhythm / Clear Fill Repeats
    description: For any sequencer steps with a current rhythm step, clear existing fills. Will not clear the display.
    group: clear-fills
    type: momentary
    index: 6
    xStart: 0
    xLength: 16
    mapping: clearFillRepeats
