name: Mutation
description: Mutations are accessed on Global page 2. Mutate melodic sequences and launch voice trading among tracks.
rows:
  -
    name: Randomizing Voices
    description: Select the voices to randomize
    group: randomizing-voices
    type: toggle
    index: 0
    xStart: 0
    xLength: 8
    mapping: toggleRandomizingVoice
    values:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
    displayValues:
      - Kick
      - Snare
      - HiHat
      - Perc
      - Bass
      - Keys
      - Pad
      - Hydra
  -
    name: Independent Mutating Voices
    description: Select the voices to mutate
    group: mutating-voices
    type: toggle
    index: 1
    xStart: 0
    xLength: 8
    mapping: toggleMutatingVoice
    values:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
    displayValues:
      - Kick
      - Snare
      - HiHat
      - Perc
      - Bass
      - Keys
      - Pad
      - Hydra
  -
    name: Trading Solo Voices
    description: Select the voices to mutate, taking turns (trading solos)
    group: trading-solos
    type: toggle
    index: 2
    xStart: 0
    xLength: 8
    mapping: toggleSoloingVoice
    values:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
    displayValues:
      - Kick
      - Snare
      - HiHat
      - Perc
      - Bass
      - Keys
      - Pad
      - Hydra
  -
    name: Randomizing Accompaniment
    description: Select the voices to add random accompaniment to
    group: randomizing-accompaniment
    type: toggle
    index: 6
    xStart: 0
    xLength: 8
    mapping: toggleRandomAccompanimentVoice
    values:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
    displayValues:
      - Kick
      - Snare
      - HiHat
      - Perc
      - Bass
      - Keys
      - Pad
      - Hydra
  -
    name: Mutation Algorithms
    description: Select the mutation algorithms used in mutation
    group: mutation-algorithms
    type: toggle
    index: 0
    xStart: 8
    xLength: 7
    mapping: toggleMutationAlgorithm
    values:
      - trps-2
      - rev
      - rot-3
      - sort
      - inv
      - inv-rev
      - bitflip
  -
    name: Toggle Mutations
    description: Enable or disable mutation mode for all tracks at the start of the next super measure. Must be on for mutations to occur
    group: mutation-controls
    type: toggle
    index: 0
    xStart: 15
    xLength: 1
    mapping: toggleMutations
  -
    name: Toggle Markovy
    description: Turn Markovy messages on/off
    group: mutation-controls
    type: toggle
    index: 1
    xStart: 15
    xLength: 1
    mapping: toggleMarkovy
