rows:
  -
    name: Super Measure Length
    index: 0
    xStart: 0
    xLength: 8
    type: meter
    mapping: updateSuperMeasure
    values:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
