name: Rhythm
rows:
  -
    name: Rhythm Pattern
    index: 0
    xStart: 0
    xLength: 16
    type: toggle
    values:
    - On
    - Off
    mapping: updateRhythm
    shiftMapping: updateBeatLength
    modifiers:
    -
      name: Step Count
      function: Update Steps
  -
    name: Note Length
    index: 6
    xStart: 0
    xLength: 8
    type: radio
    mapping: updateNoteLength
    values:
      - 16n
      - 8n
      - 8nd
      - 4n
      - 4nd
      - 2n
      - 2nd
      - 1n
modifiers:
  row: 6
  start: 8
  length: 8
  keys:
  -
    function: Rhythm Type
    type: toggle
    values:
    - Manual
    - Euclidean
  -
    function: Modifier 1
    type: toggle
    values:
    - Random
    - Recursive
  -
    function: Modifier 2
    type: toggle
    values:
    - Random
    - Recursive
  -
    function: undefined
  -
    function: undefined
  -
    function: Step Count
    type: momentary
    values:
    - On
    - Off
  -
    function: Weighted
    type: toggle
    values:
    - On
    - Off
  -
    function: Generate
    type: momentary
