name: Shift Register Algorithm
description: Configure the shift register algorithm
rows:
  -
    name: Length
    description: set the shift register length
    group: shift-reg-length
    type: meter
    index: 2
    xStart: 0
    xLength: 4
    mapping: setShiftRegisterLength
  -
    name: Octave Range
    description: set the shift register output octave range
    group: shift-reg-octave-range
    type: range
    index: 2
    xStart: 8
    xLength: 8
    mapping: setOctaveRange
  -
    name: Algorithms
    description: select the current algorithm
    group: algorithms
    type: radio
    index: 6
    xStart: 0
    xLength: 16
    mapping: setAlgorithm
    values:
      - simple
      - shift_reg
      - inf_series
  -
    name: Advance
    description: advance the current algorithm 1 iteration
    group: advance
    type: momentary
    index: 6
    xStart: 15
    xLength: 1
    mapping: advance
