name: Drum Pad
description: The drum pad is accessed on rhythm page 4. Maps to an Ableton Drum Rack.
matrices:
  -
    name: Rhythm Pattern / Step Length
    description: Turn rhythm gate steps on/off; when shift key is on, sets the rhythm step length
    group: rhythm-pattern
    type: toggle / meter
    rowStart: 0
    rowEnd: 1
    columnStart: 0
    columnEnd: 15
    mapping: selectGate
    shiftMapping: updateStepLength
  -
    name: Drum Pads
    description: Each button corresponds to a drum rack voice.
    group: drum-pad
    type: momentary
    rowStart: 3
    rowEnd: 6
    columnStart: 0
    columnEnd: 3
    mapping: triggerDrumPad
    rowValues:
      -
        - 48
        - 49
        - 50
        - 51
      -
        - 44
        - 45
        - 46
        - 47
      -
        - 40
        - 41
        - 42
        - 43
      -
        - 36
        - 37
        - 38
        - 39
rows:
  -
    shiftName: Update Rhythm Parameters
    shiftDescription: Set parameters based on the current rhythm algorithm
    shiftGroup: rhythm-algorithms
    index: 2
    xStart: 0
    xLength: 16
    mapping: updateRhythmParameters
  -
    name: Clear All Gates
    description: Remove all active gates (clear rhythm)
    group: clear-gates
    index: 3
    xStart: 15
    xLength: 1
    mapping: clearAllGates
  -
    name: Toggle Note Playing
    description: When enabled, when the pad buttons are pressed, the note will be played in Live
    group: drum-rack-controls
    type: toggle
    index: 3
    xStart: 4
    xLength: 1
    mapping: toggleNotePlaying
  -
    name: Toggle Note Recording
    description: When enabled, when a gate button and pad buttons are pressed, the note will be recorded into the current sequencer step for the gate
    group: drum-rack-controls
    type: toggle
    index: 4
    xStart: 4
    xLength: 1
    mapping: toggleNoteRecording
  -
    name: Pulse Rate
    description: Set the current track's pulse rate between 16n and 2n
    group: pulse-rate
    type: radio
    index: 4
    xStart: 8
    xLength: 4
    mapping: updatePulse
    values:
      - 16n
      - 8n
      - 4n
      - 2n
  -
    name: Note Length
    description: Set the length of sequencer notes
    group: note-length
    type: meter
    index: 5
    xStart: 8
    xLength: 8
    mapping: updateNoteLength
    values:
      - 16n
      - 8n
      - 8nd
      - 4n
      - 4nd
      - 2n
      - 2nd
      - 1n
  -
    name: Default Probability
    description: Set the current track's default gate probability
    group: default-prob
    type: meter
    index: 6
    xStart: 8
    xLength: 8
    mapping: updateDefaultProbability
    values:
      - 0.125
      - 0.25
      - 0.375
      - 0.5
      - 0.625
      - 0.75
      - 0.875
      - 1
