name: Melodic Vectors
description: Melodic vectors are accessed on Melody page 3. Apply shifts to a sequence of notes.
matrices:
  -
    name: Shift Step
    description: Sets the melodic vector shift for a step
    group: shift-steps
    type: bipolar vertical meter
    rowStart: 0
    rowEnd: 6
    columnStart: 0
    columnEnd: 11
    mapping: setStepShift
    columnValues:
      - 7
      - 6
      - 5
      - 4
      - 3
      - 2
      - 1
    shiftColumnValues:
      - -1
      - -2
      - -3
      - -4
      - -5
      - -6
      - -7
  -
    name: Shift Sequence Length
    description: Sets the number of steps in the shift sequence between 1 and 12
    group: shift-sequence
    type: multi-row meter
    rowStart: 0
    rowEnd: 2
    columnStart: 12
    columnEnd: 15
    mapping: setShiftSequenceLength
    rowValues:
      -
        - 1
        - 2
        - 3
        - 4
      -
        - 5
        - 6
        - 7
        - 8
      -
        - 9
        - 10
        - 11
        - 12

