name: Global
description: Manage global properties like track active chains, super measure length, scale and tonic.
rows:
  -
    name: Super Measure Length
    description: Set the super measure length between 1 and 8 measures
    group: super-measure
    index: 0
    xStart: 8
    xLength: 8
    type: meter
    mapping: updateSuperMeasure
    values:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
matrices:
  -
    name: Track Chains
    description: Set the active chain for each track
    group: track-chains
    type: row-radio
    rowStart: 0
    rowEnd: 6
    columnStart: 0
    columnEnd: 7
    mapping: setTrackChain
  -
    name: Tonic
    description: Set the global tonic
    group: scale-tonic
    type: radio
    rowStart: 1
    rowEnd: 3
    columnStart: 8
    columnEnd: 11
    mapping: setTonic
    rowValues:
      -
        - 0
        - 1
        - 2
        - 3
      -
        - 4
        - 5
        - 6
        - 7
      -
        - 8
        - 9
        - 10
        - 11
    rowDisplayValues:
      -
        - C
        - C#
        - D
        - D#
      -
        - E
        - F
        - F#
        - G
      -
        - G#
        - A
        - A#
        - B
  -
    name: Scale
    description: Set the global scale
    group: scale
    type: radio
    rowStart: 1
    rowEnd: 3
    columnStart: 12
    columnEnd: 15
    mapping: setScale
    rowValues:
      -
        - Major
        - Minor
        - Dorian
        - Phrygian
      -
        - Lydian
        - Mixolydian
        - Locrian
        - MajPentatonic
      -
        - MinPentatonic
        - WholeTone
        - GS
        - Chromatic
  -
    name: Beats
    description: Predefined beat patterns for multiple tracks
    gropu: beats
    type: radio
    rowStart: 4
    rowEnd: 6
    columnStart: 8
    columnEnd: 15
    mapping: setBeat
    rowValues:
      -
        - electro/base
        - electro/base_with_hats
        - electro/siberian_nights
        - electro/new_wave
