name: Algorithms
description: Edit the track algorithms
rows:
  -
    name: Algorithms
    description: select the current algorithm
    group: algorithms
    type: radio
    index: 6
    xStart: 0
    xLength: 16
    mapping: setAlgorithm
    values:
      - simple
      - shift_reg
      - inf_series
  -
    name: Advance
    description: advance the current algorithm 1 iteration
    group: advance
    type: momentary
    index: 6
    xStart: 15
    xLength: 1
    mapping: advance
