name: Melody
description: Add melodies to the active track. Select input notes from the current scale and process the input sequence through a melody algorithm.
matrices:
  -
    name: Keyboard Octave
    description: Button represents a melody note; first button in the row is the current scale's tonic for the row's octave
    group: melody-notes
    type: momentary
    rowStart: 0
    rowEnd: 6
    columnStart: 0
    columnEnd: 13
    mapping: addNote
    columnValues:
      - 6
      - 5
      - 4
      - 3
      - 2
      - 1
      - 0
rows:
  -
    name: Toggle Input Melody Recording
    description: Turn melody recording on/off; when turning on, the queued melody progression clears
    group: melody-recording-controls
    type: toggle
    index: 0
    xStart: 15
    xLength: 1
    mapping: toggleMelodyRecording
  -
    name: Remove Last Input Melody Note
    description: Remove the last note from the currently queued melody
    group: melody-recording-controls
    type: momentary
    index: 1
    xStart: 15
    xLength: 1
    mapping: removeLastNote
  -
    name: Toggle Create Clip Mode
    description: When on, will add the melody to the next clip
    group: melody-recording-controls
    type: toggle
    index: 2
    xStart: 15
    xLength: 1
    mapping: toggleNewClipCreation
  -
    name: Toggle Vector Shifts
    description: When on, after processing by the melody algorithm, it will be processed by the melodic vector shifts
    group: melody-recording-controls
    type: toggle
    index: 3
    xStart: 15
    xLength: 1
    mapping: toggleVectorShifts
  -
    name: Generate Melody
    description: Generates melody for currently selected track equal to the global queued input melody
    group: melody-algorithms
    type: momentary
    index: 0
    xStart: 14
    xLength: 1
    mapping: generateMelody
    value: simple
  -
    name: Generate Melody
    description: Generates melody for currently selected track equal to the global queued input melody
    group: melody-algorithms
    type: momentary
    index: 1
    xStart: 14
    xLength: 1
    mapping: generateMelody
    value: self_replicate
  -
    name: Generate Melody
    description: Generates melody for currently selected track equal to the global queued input melody
    group: melody-algorithms
    type: momentary
    index: 2
    xStart: 14
    xLength: 1
    mapping: generateMelody
    value: counted
  -
    name: Generate Melody
    description: Generates melody for currently selected track equal to the global queued input melody
    group: melody-algorithms
    type: momentary
    index: 3
    xStart: 14
    xLength: 1
    mapping: generateMelody
    value: zig_zag
