name: Rhythm
description: Manage the sequencer rhythm steps for the active track. Turn steps on and manage sequence step lengths.
rows:
  -
    name: Rhythm Pattern / Step Length
    description: Turn rhythm gate steps on/off; when shift key is on, sets the rhythm step length
    group: rhythm-pattern
    type: toggle / meter
    index: 0
    xStart: 0
    xLength: 16
    mapping: updateRhythm
    shiftMapping: updateBeatLength
  -
    name: Pulse Rate
    description: Set the current track's pulse rate between 16n and 2n
    group: pulse-rate
    type: radio
    index: 5
    xStart: 0
    xLength: 4
    mapping: updatePulse
    values:
      - 16n
      - 8n
      - 4n
      - 2n
  -
    name: Note Length
    description: Set the length of sequencer notes
    group: note-length
    type: radio
    index: 6
    xStart: 0
    xLength: 8
    mapping: updateNoteLength
    values:
      - 16n
      - 8n
      - 8nd
      - 4n
      - 4nd
      - 2n
      - 2nd
      - 1n
