name: Ramps
description: Generate ramp sequences for the active track.
rows:
  -
    name: Outer Divisions
    description: Turn rhythm gate steps on/off; when shift key is on, sets the rhythm step length
    group: outer-divs
    type: toggle
    index: 0
    xStart: 0
    xLength: 16
    mapping: updateSegment
  -
    name: Inner Divisions
    description: Set the cycle length for the corresponding outer division
    group: inner-divs
    type: meter
    index: 1
    xStart: 0
    xLength: 16
    mapping: updateSubdivision
  -
    name: Ramp Range
    description: Set the 0-1 range for the currently active outer ramp
    group: ramp-range
    type: range
    index: 2
    xStart: 0
    xLength: 16
    mapping: updateRange
  -
    name: Ramp Sequence Index
    description: Select between the first and second ramp sequences for the active track
    group: ramp-seq-index
    type: radio
    index: 6
    xStart: 0
    xLength: 2
    mapping: updateActiveRampSequenceIndex
  -
    name: Activate Ramp Index
    description: Toggle the currently selected ramp sequence on or off
    group: ramp-seq-active
    type: toggle
    index: 6
    xStart: 2
    xLength: 1
    mapping: toggleRampSequence
  -
    name: Active Segment Inverted
    description: Lights up when the active segment ramps from high to low
    group: active-segment-high-to-low
    type: indicator
    index: 6
    xStart: 3
    xLength: 1
    mapping: ignoredIndicator
