name: Drum Pad
description: The drum pad is accessed on rhythm page 4. Maps to an Ableton Drum Rack.
matrices:
  -
    name: Drum Pads
    description: Each button corresponds to a drum rack voice.
    group: drum-pad
    type: momentary
    rowStart: 2
    rowEnd: 5
    columnStart: 0
    columnEnd: 3
    mapping: triggerDrumPad
    rowValues:
      -
        - 48
        - 49
        - 50
        - 51
      -
        - 44
        - 45
        - 46
        - 47
      -
        - 40
        - 41
        - 42
        - 43
      -
        - 36
        - 37
        - 38
        - 39
rows:
  -
    name: Rhythm Pattern / Step Length
    description: Turn rhythm gate steps on/off; when shift key is on, sets the rhythm step length
    group: rhythm-pattern
    type: toggle / meter
    index: 0
    xStart: 0
    xLength: 16
    mapping: selectGate
    shiftMapping: updateStepLength
  -
    name: Toggle Note Playing
    description: When enabled, when the pad buttons are pressed, the note will be played in Live
    group: drum-rack-controls
    type: toggle
    index: 6
    xStart: 0
    xLength: 1
    mapping: toggleNotePlaying
  -
    name: Toggle Note Recording
    description: When enabled, when the pad buttons are pressed, the note will be recorded into the current sequencer step
    group: drum-rack-controls
    type: toggle
    index: 6
    xStart: 1
    xLength: 1
    mapping: toggleNoteRecording
