name: Rhythm
description: Manage the sequencer rhythm steps for the active track. Turn steps on and manage sequence step lengths.
matrices:
  -
    name: Rhythm Pattern / Step Length
    description: Turn rhythm gate steps on/off; when shift key is on, sets the rhythm step length
    group: rhythm-pattern
    type: toggle / meter
    rowStart: 0
    rowEnd: 1
    columnStart: 0
    columnEnd: 15
    mapping: updateRhythm
    shiftMapping: updateStepLength
rows:
  -
    shiftName: Toggle Fills for Measure
    shiftDescription: The sub-measures of the super measure on which the fill will happen.
    shiftGroup: fill-measures
    shiftType: toggle
    index: 2
    xStart: 0
    xLength: 8
    mapping: toggleFillMeasure
    displayValues:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
  -
    shiftName: Fill Duration
    shiftDescription: The length of time in which to spread a rhythmic fill.
    shiftGroup: fill-duration
    shiftType: meter
    index: 2
    xStart: 8
    xLength: 8
    mapping: setFillDuration
    values:
      - 16n
      - 16nd
      - 8n
      - 8nd
      - 4n
      - 4nd
      - 2n
      - 2nd
  -
    name: Rhythm Parameter Row
    description: Set parameter values for the current algorithm
    type: mixed
    index: 3
    xStart: 0
    xLength: 16
    mapping: updateRhythmParameter
    shiftMapping: updateAlternateRhythmParameter
  -
    name: Rhythm Algorithms
    description: Set the current rhythm algorithm
    group: rhythm-algorithm
    type: radio
    index: 6
    xStart: 0
    xLength: 8
    mapping: updateRhythmAlgorithm
    values:
      - manual
      - surround
      - accelerating
      - undefined
      - undefined
      - undefined
      - undefined
      - undefined
  -
    name: Related Track
    description: Set the current track's related rhythm track
    group: related-rhythm
    type: radio
    index: 5
    xStart: 0
    xLength: 7
    mapping: updateRelatedRhythmTrack
  -
    name: Pulse Rate
    description: Set the current track's pulse rate between 16n and 2n
    group: pulse-rate
    type: radio
    index: 4
    xStart: 8
    xLength: 4
    mapping: updatePulse
    values:
      - 16n
      - 8n
      - 4n
      - 2n
  -
    name: Note Length
    description: Set the length of sequencer notes
    group: note-length
    type: meter
    index: 5
    xStart: 8
    xLength: 8
    mapping: updateNoteLength
    values:
      - 16n
      - 8n
      - 8nd
      - 4n
      - 4nd
      - 2n
      - 2nd
      - 1n
  -
    name: Default Probability
    description: Set the current track's default gate probability
    group: default-prob
    type: meter
    index: 6
    xStart: 8
    xLength: 8
    mapping: updateDefaultProbability
    values:
      - 0.125
      - 0.25
      - 0.375
      - 0.5
      - 0.625
      - 0.75
      - 0.875
      - 1
