type: beats
groups:
  electro:
    name: Electro
    beats:
      base:
        name: Electro Base
        length: 32
        voices:
          -
            track: Kick
            hits:       [0,    6,  16, 22, 26, 29]
            velocities: [1, 0.75, 1, 0.75, 0.875, 0.625]
          -
            track: Snare
            hits:       [4,  12, 20, 28]
            velocities: [0.75, 0.875, 0.75, 0.875]
          -
            track: Perc 1
            hits:       []
            velocities: []
      base_with_hats:
        name: Electro w/ Hats
        length: 32
        voices:
          -
            track: Kick
            hits:       [0,    6,  16, 22, 26, 29]
            velocities: [1, 0.75, 1, 0.75, 0.875, 0.625]
          -
            track: Snare
            hits:       [4,  12, 20, 28]
            velocities: [0.75, 0.875, 0.75, 0.875]
          -
            track: Perc 1
            hits:       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
            velocities: [0.75, 0.375, 0.375, 0.625, 0.5, 0.375, 0.75, 0.375, 0.375, 0.375, 0.625, 0.25, 0.75, 0.25, 0.25, 0.375, 0.75, 0.375, 0.375, 0.625, 0.5, 0.375, 0.75, 0.375, 0.375, 0.375, 0.625, 0.25, 0.75, 0.25, 0.25, 0.375]
      siberian_nights:
        name: Siberian Nights
        length: 16
        voices:
          -
            track: Kick
            hits:       [0,    6]
            velocities: [1, 0.75]
          -
            track: Snare
            hits:       [4,  12]
            velocities: [0.75, 0.875]
          -
            track: Perc 1
            hits:       [0,   2,  3,  4,  6,  7,  8, 10, 11, 12, 14, 15]
            velocities: [0.75, 0.375, 0.625, 0.625, 0.25, 0.75, 0.375, 0.625, 0.25, 0.625, 0.25, 0.5]
      new_wave:
        name: New Wave
        length: 16
        voices:
          -
            track: Kick
            hits:       [0,    6,  8,  9]
            velocities: [1, 0.75, 0.5, 0.5]
          -
            track: Snare
            hits:       [4,  12]
            velocities: [0.75, 0.875]
          -
            track: Perc 1
            hits:       [0,   1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]
            velocities: [0.75, 0.375, 0.375, 0.625, 0.375, 0.375, 0.75, 0.375, 0.375, 0.375, 0.625, 0.25, 0.75, 0.25, 0.25, 0.25]
  techno:
    name: Techno
    beats:
      base:
        name: 4 to the Floor
        length: 16
        voices:
          -
            track: Kick
            hits:       [0,    4,  8, 12]
            velocities: [1, 0.5, 0.5, 0.625]
          -
            track: Snare
            hits:       []
            velocities: []
          -
            track: Perc 1
            hits:       []
            velocities: []
      house:
        name: House
        length: 16
        voices:
          -
            track: Kick
            hits:       [0,    4,  8, 12]
            velocities: [1, 0.625, 0.625, 0.625]
          -
            track: Snare
            hits:       [4,  12]
            velocities: [0.75, 0.75]
          -
            track: Perc 1
            hits:       [2,   6, 10, 14]
            velocities: [0.25, 0.375, 0.375, 0.375]
      footwork:
        name: Footwork
        length: 32
        voices:
          -
            track: Kick
            hits:       [0,    3,  6,  8, 11, 14,  16, 19, 22, 24, 27, 30]
            velocities: [1, 0.375, 0.375, 0.5, 0.75, 0.375, 1, 0.375, 0.375, 0.5, 0.75, 0.375]
          -
            track: Snare
            hits:       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
            velocities: [0.5, 0.375, 0.25, 0.25, 0.5, 0.625, 0.5, 0.375, 0.375, 0.625, 0.625, 0.5, 0.25, 0.25, 0.25, 0.25, 0.375, 0.25, 0.25, 0.25, 0.25, 0.25, 0.25, 0.375, 0.625, 0.875, 0.5, 0.375, 0.375, 0.375, 0.25, 0.25]
          -
            track: Perc 1
            hits:       [2,  10, 18, 22, 23, 26,  30]
            velocities: [0.25, 0.375, 0.25, 0.375, 0.375, 0.875, 1]
      dubstep:
        name: Dubstep
        length: 32
        voices:
          -
            track: Kick
            hits:       [0,  10,  16, 19, 22, 26]
            velocities: [1, 0.625, 1, 0.375, 0.375, 0.5]
          -
            track: Snare
            hits:       [8,  24]
            velocities: [0.75, 0.75]
          -
            track: Perc 1
            hits:       [1,   2,  4,  6, 11, 13, 14, 17, 18, 20, 22, 27, 29, 30]
            velocities: [0.25, 0.25, 0.375, 0.375, 0.25, 0.25, 0.375, 0.375, 0.25, 0.25, 0.375, 0.375, 0.25, 0.25]
  hip_hop:
    name: Hip Hop
    beats:
      base:
        name: Hip Hop Base
        length: 16
        voices:
          -
            track: Kick
            hits:       [0,    2,  6,  7, 14]
            velocities: [1, 0.75, 0.625, 0.625, 0.75]
          -
            track: Snare
            hits:       [4,  12]
            velocities: [0.75, 0.875]
          -
            track: Perc 1
            hits:       [0,   2,  3,  4,  6,  7,  8, 10, 11, 12, 14, 15]
            velocities: [0.75, 0.375, 0.625, 0.625, 0.25, 0.75, 0.375, 0.625, 0.25, 0.625, 0.25, 0.5]
      hip_hop_4:
        name: Hip Hop 4
        length: 32
        voices:
          -
            track: Kick
            hits:       [0,    3,  7,  9, 10, 15,  16, 18, 23, 24, 25, 26]
            velocities: [1, 0.75, 0.5, 0.5, 0.75, 0.5, 1, 0.75, 0.5, 0.875, 0.5, 0.75]
          -
            track: Snare
            hits:       [4,  12, 20, 28]
            velocities: [0.75, 0.875, 0.75, 0.875]
          -
            track: Perc 1
            hits:       []
            velocities: []
      hip_hop_7:
        name: Hip Hop 7
        length: 16
        voices:
          -
            track: Kick
            hits:       [0,    7, 10, 13, 15]
            velocities: [1, 0.5, 0.75, 0.5, 0.5]
          -
            track: Snare
            hits:       [4,  12]
            velocities: [0.75, 0.875]
          -
            track: Perc 1
            hits:       [0,   2,  4,  6,  8, 10, 12, 14]
            velocities: [0.75, 0.375, 0.625, 0.25, 0.375, 0.625, 0.625, 0.25]
      hip_hop_8:
        name: Hip Hop 8
        length: 16
        voices:
          -
            track: Kick
            hits:       [0,    3,  8, 10, 11]
            velocities: [1, 0.5, 0.875, 0.5, 0.75]
          -
            track: Snare
            hits:       [4,  12]
            velocities: [0.75, 0.875]
          -
            track: Perc 1
            hits:       [ 0,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]
            velocities: [0.75, 0.375, 0.625, 0.5, 0.875, 0.75, 0.375, 0.375, 0.375, 0.625, 0.25, 0.625, 0.875, 0.25, 0.375]
      funky_drummer:
        name: Funky Drummer
        length: 16
        voices:
          -
            track: Kick
            hits:       [0,    2,  6, 10, 13]
            velocities: [1, 0.5, 0.875, 0.75, 0.5]
          -
            track: Snare
            hits:       [4,   7,  9, 11, 12]
            velocities: [0.75, 0.5, 0.5, 0.5, 0.875]
          -
            track: Perc 1
            hits:       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]
            velocities: [0.75, 0.375, 0.375, 0.625, 0.5, 0.375, 0.75, 0.375, 0.875, 0.375, 0.625, 0.25, 0.75, 0.875, 0.25, 0.375]
      amen_break:
        name: Amen Break
        length: 32
        voices:
          -
            track: Kick
            hits:       [0,    2, 10, 11,  16, 18, 26]
            velocities: [1, 0.75, 0.5, 0.5, 1, 0.75, 0.75]
          -
            track: Snare
            hits:       [4,   7,  9, 12, 15, 17, 20, 23, 25, 30]
            velocities: [0.75, 0.25, 0.25, 0.875, 0.5, 0.375, 0.75, 0.5, 0.625, 0.75]
          -
            track: Perc 1
            hits:       [0,   2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]
            velocities: [0.75, 0.375, 0.625, 0.25, 0.375, 0.625, 0.625, 0.25, 0.75, 0.375, 0.625, 0.25, 0.375, 0.875, 0.625, 0.25]
      funky_president:
        name: Funky President
        length: 16
        voices:
          -
            track: Kick
            hits:       [0,    2,  6,  7,  8, 10, 13, 14]
            velocities: [1, 0.5, 0.875, 0.25, 0.875, 0.75, 0.5, 0.75]
          -
            track: Snare
            hits:       [4,   7,  9, 11, 12, 15]
            velocities: [0.75, 0.5, 0.5, 0.5, 0.875, 0.5]
          -
            track: Perc 1
            hits:       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]
            velocities: [0.75, 0.375, 0.375, 0.625, 0.5, 0.375, 0.75, 0.375, 0.875, 0.375, 0.875, 0.25, 0.75, 0.875, 0.25, 0.375]
      levee:
        name: Levee Breaks
        length: 16
        voices:
          -
            track: Kick
            hits:       [0,    1,  7, 10, 11]
            velocities: [1, 0.25, 0.25, 0.75, 0.5]
          -
            track: Snare
            hits:       [4,  12]
            velocities: [0.75, 0.875]
          -
            track: Perc 1
            hits:       [0,   2,  4,  6,  8, 10, 12, 14]
            velocities: [0.75, 0.375, 0.625, 0.25, 0.375, 0.625, 0.625, 0.25]
      big_beat:
        name: Big Beat
        length: 16
        voices:
          -
            track: Kick
            hits:       [0,    3,  6,  8]
            velocities: [1, 0.25, 0.75, 0.75]
          -
            track: Snare
            hits:       [4,  12]
            velocities: [0.75, 0.875]
          -
            track: Perc 1
            hits:       []
            velocities: []
