type: beats
groups:
  electro:
    name: Electro
    beats:
      base:
        name: Electro Base
        length: 32
        voices:
          -
            track: Kick
            hits:       [0,    6,  16, 22, 26, 29]
            velocities: [100, 80, 100, 80, 95, 75]
          -
            track: Snare
            hits:       [4,  12, 20, 28]
            velocities: [80, 90, 80, 95]
          -
            track: HiHat
            hits:       []
            velocities: []
      base_with_hats:
        name: Electro w/ Hats
        length: 32
        voices:
          -
            track: Kick
            hits:       [0,    6,  16, 22, 26, 29]
            velocities: [100, 80, 100, 80, 95, 75]
          -
            track: Snare
            hits:       [4,  12, 20, 28]
            velocities: [80, 90, 80, 95]
          -
            track: HiHat
            hits:       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
            velocities: [80, 44, 44, 70, 55, 44, 80, 44, 44, 44, 70, 30, 80, 30, 30, 44, 80, 44, 44, 70, 55, 44, 80, 44, 44, 44, 70, 30, 80, 30, 30, 44]
      siberian_nights:
        name: Siberian Nights
        length: 16
        voices:
          -
            track: Kick
            hits:       [0,    6]
            velocities: [100, 80]
          -
            track: Snare
            hits:       [4,  12]
            velocities: [80, 90]
          -
            track: HiHat
            hits:       [0,   2,  3,  4,  6,  7,  8, 10, 11, 12, 14, 15]
            velocities: [80, 44, 75, 78, 35, 80, 50, 75, 35, 70, 30, 55]
      new_wave:
        name: New Wave
        length: 16
        voices:
          -
            track: Kick
            hits:       [0,    6,  8,  9]
            velocities: [100, 80, 55, 58]
          -
            track: Snare
            hits:       [4,  12]
            velocities: [80, 90]
          -
            track: HiHat
            hits:       [0,   1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]
            velocities: [80, 44, 44, 70, 44, 44, 80, 44, 44, 44, 70, 30, 80, 30, 30, 30]
          -
            track: Perc
            hits:       [4,  12]
            velocities: [80, 90]
  hip_hop:
    name: Hip Hop
    beats:
      base:
        name: Hip Hop Base
        length: 16
        voices:
          -
            track: Kick
            hits:       [0,    2,  6,  7, 14]
            velocities: [100, 80, 70, 75, 80]
          -
            track: Snare
            hits:       [4,  12]
            velocities: [80, 90]
          -
            track: HiHat
            hits:       [0,   2,  3,  4,  6,  7,  8, 10, 11, 12, 14, 15]
            velocities: [80, 44, 75, 78, 35, 80, 50, 75, 35, 70, 30, 55]
      hip_hop_4:
        name: Hip Hop 4
        length: 32
        voices:
          -
            track: Kick
            hits:       [0,    3,  7,  9, 10, 15,  16, 18, 23, 24, 25, 26]
            velocities: [100, 80, 60, 60, 80, 60, 100, 80, 60, 90, 60, 80]
          -
            track: Snare
            hits:       [4,  12, 20, 28]
            velocities: [80, 90, 80, 95]
          -
            track: HiHat
            hits:       []
            velocities: []
      hip_hop_7:
        name: Hip Hop 7
        length: 16
        voices:
          -
            track: Kick
            hits:       [0,    7, 10, 13, 15]
            velocities: [100, 60, 80, 60, 60]
          -
            track: Snare
            hits:       [4,  12]
            velocities: [80, 90]
          -
            track: HiHat
            hits:       [0,   2,  4,  6,  8, 10, 12, 14]
            velocities: [80, 44, 78, 35, 50, 75, 70, 30]
      hip_hop_8:
        name: Hip Hop 8
        length: 16
        voices:
          -
            track: Kick
            hits:       [0,    3,  8, 10, 11]
            velocities: [100, 60, 90, 60, 80]
          -
            track: Snare
            hits:       [4,  12]
            velocities: [80, 90]
          -
            track: HiHat
            hits:       [ 0,  1,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]
            velocities: [80, 44, 70, 55, 90, 80, 44, 44, 44, 70, 30, 70, 90, 30, 44]
      funky_drummer:
        name: Funky Drummer
        length: 16
        voices:
          -
            track: Kick
            hits:       [0,    2,  6, 10, 13]
            velocities: [100, 60, 90, 80, 60]
          -
            track: Snare
            hits:       [4,   7,  9, 11, 12]
            velocities: [80, 60, 60, 60, 90]
          -
            track: HiHat
            hits:       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]
            velocities: [80, 44, 44, 70, 55, 44, 80, 44, 90, 44, 70, 30, 80, 90, 30, 44]
      amen_break:
        name: Amen Break
        length: 32
        voices:
          -
            track: Kick
            hits:       [0,    2, 10, 11,  16, 18, 26]
            velocities: [100, 80, 60, 60, 100, 80, 80]
          -
            track: Snare
            hits:       [4,   7,  9, 12, 15, 17, 20, 23, 25, 30]
            velocities: [80, 30, 30, 90, 60, 40, 80, 60, 70, 80]
          -
            track: HiHat
            hits:       [0,   2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30]
            velocities: [80, 44, 78, 35, 50, 75, 70, 30, 80, 44, 78, 35, 50, 95, 70, 30]
      funky_president:
        name: Funky President
        length: 16
        voices:
          -
            track: Kick
            hits:       [0,    2,  6,  7,  8, 10, 13, 14]
            velocities: [100, 60, 90, 30, 90, 80, 60, 80]
          -
            track: Snare
            hits:       [4,   7,  9, 11, 12, 15]
            velocities: [80, 60, 60, 60, 90, 60]
          -
            track: HiHat
            hits:       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]
            velocities: [80, 44, 44, 70, 55, 44, 80, 44, 90, 44, 90, 30, 80, 90, 30, 44]
      levee:
        name: Levee Breaks
        length: 16
        voices:
          -
            track: Kick
            hits:       [0,    1,  7, 10, 11]
            velocities: [100, 30, 30, 80, 60]
          -
            track: Snare
            hits:       [4,  12]
            velocities: [80, 90]
          -
            track: HiHat
            hits:       [0,   2,  4,  6,  8, 10, 12, 14]
            velocities: [80, 44, 78, 35, 50, 75, 70, 30]
      big_beat:
        name: Big Beat
        length: 16
        voices:
          -
            track: Kick
            hits:       [0,    3,  6,  8]
            velocities: [100, 30, 80, 80]
          -
            track: Snare
            hits:       [4,  12]
            velocities: [80, 90]
          -
            track: HiHat
            hits:       []
            velocities: []
