type: beats
groups:
  electro:
    name: Electro
    beats:
      base:
        name: Electro Base
        length: 32
        voices:
          -
            track: Kick
            hits:       [0,    6,  16, 22, 26, 29]
            velocities: [100, 80, 100, 80, 95, 75]
          -
            track: Snare
            hits:       [4,  12, 20, 28]
            velocities: [80, 90, 80, 95]
      base_with_hats:
        name: Electro w/ Hats
        length: 32
        voices:
          -
            track: Kick
            hits:       [0,    6,  16, 22, 26, 29]
            velocities: [100, 80, 100, 80, 95, 75]
          -
            track: Snare
            hits:       [4,  12, 20, 28]
            velocities: [80, 90, 80, 95]
          -
            track: HiHat
            hits:       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31]
            velocities: [80, 44, 44, 70, 55, 44, 80, 44, 44, 44, 70, 30, 80, 30, 30, 44, 80, 44, 44, 70, 55, 44, 80, 44, 44, 44, 70, 30, 80, 30, 30, 44]
      siberian_nights:
        name: Siberian Nights
        length: 16
        voices:
          -
            track: Kick
            hits:       [0,    6]
            velocities: [100, 80]
          -
            track: Snare
            hits:       [4,  12]
            velocities: [80, 90]
          -
            track: HiHat
            hits:       [0,   2,  3,  4,  6,  7,  8, 10, 11, 12, 14, 15]
            velocities: [80, 44, 75, 78, 35, 80, 50, 75, 35, 70, 30, 55]
      new_wave:
        name: New Wave
        length: 16
        voices:
          -
            track: Kick
            hits:       [0,    6,  8,  9]
            velocities: [100, 80, 55, 58]
          -
            track: Snare
            hits:       [4,  12]
            velocities: [80, 90]
          -
            track: HiHat
            hits:       [0,   1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15]
            velocities: [80, 44, 44, 70, 44, 44, 80, 44, 44, 44, 70, 30, 80, 30, 30, 30]
          -
            track: Perc
            hits:       [4,  12]
            velocities: [80, 90]
