live_tracks:
  -
    name: Base Kits
    type: DrumTrack
    dawIndex: 0
    rampSequencer: false
    chains:
      -
        name: Techno Kit
        type: drum rack
        pads:
          - Kick 4-4 Soft
          - Snare 808 2
          - HiHat 909 Closed
          - Clap 707
          - Kick BNYX 1
          - Rim GR
          - HiHat Closed Modular Salient
          - Clap Feel
          - Kick Boxer
          - Snare African Dream
          - Snare Dubplate
          - Snare Object
          - Kick Boxed
          - Snare Alley
          - Snare Keep Tight
          - Snare Object Night
      -
        name: Hip Hop Kit
        type: drum rack
        pads:
          - Kick Flared Out
          - Snare DMX Core
          - HiHat Closed Cristal
          - HiHat Open 53 TL
          - Kick 70s 4
          - Clap 707
          - Rim Something
          - Cowbell LDre 2
          - Kick Fat Matt Break
          - Snare 70s MPC 4
          - Rim Vinyl 2
          - Ginger Drums 1
          - Kick Feel
          - Clap Perc Combo
          - Bongo Break Chop
          - Crash 909
      -
        name: Synthetic Kit
        type: drum rack
        pads:
          - Kick 4-4 Soft SpectRes 1
          - Snare-Object-28
          - Hihat Closed Metallic Charred
          - E-Perc Click Chop
          - Kick 4-4 Soft SpectRes 2
          - Snare Support
          - Bell Ring ER Fenk 1
          - E-Perc BittyBot
          - Kick 4-4 Soft SpectRes 3
          - Synth-Pulse-43
          - Bell Reso Noise 3
          - E-Perc Beetle Talk
          - Kick 4-4 Soft SpectRes 4
          - Kick Leaner
          - Cowbell Fenk Chick
          - E-Perc Tiny Cavern Anvil
      -
        name: 505 Core Kit
        type: drum rack
        pads:
          - Bassdrum
          - Snaredrum
          - Closed Hi Hat
          - Handclap
          - Conga Lo
          - Timbale
          - Rimshot
          - Conga Hi
          - Tom Lo
          - Tom Mid
          - Open Hi Hat
          - Tom Hi
          - Cowbell Lo
          - Crash
          - Hi Cowbell
          - Ride
      -
        name: 606 Core Kit
        type: drum rack
        pads:
          - Bassdrum
          - Snare
          - Closed Hi Hat
          - Snare
          - Snare Mod
          - Kick Mod
          - Snare
          - Tom Low
          - Hihat Combo
          - Tom Mid
          - Open Hi Hat
          - Tom Hi
          - Tom Hi
          - Cymbal
          - Cymbal
          - Cymbal Mod
      -
        name: 707 Core Kit
        type: drum rack
        pads:
          - Bassdrum
          - Snare
          - Closed Hi Hat
          - Handclap
          - Snare
          - Kick
          - Rimshot
          - Tom Low
          - Tamb
          - Tom Low
          - Open Hi Hat
          - Tom Mid
          - Tom Hi
          - Crash
          - Cowbell
          - Ride
      -
        name: 808 Core Kit
        type: drum rack
        pads:
          - Bass Drum
          - Snare Drum
          - Closed Hi Hat
          - Hand Clap
          - Low Conga
          - Mid Conga
          - Rim Shot
          - Hi Conga
          - Low Tom
          - Mid Tom
          - Open Hi Hat
          - Hi Tom
          - Maracas
          - Cymbal
          - Cow Bell
          - Claves
      -
        name: 909 Core Kit
        type: drum rack
        pads:
          - Bass Drum
          - Snare Drum
          - Closed Hi Hat
          - Hand Clap
          - Bass Drum
          - Snare Drum
          - Rim Shot
          - Snare Drum
          - Low Tom
          - Mid Tom
          - Open Hi Hat
          - Hi Tom
          - Crash
          - Crash
          - Ride
          - Ride
  -
    name: Perc 0
    type: DrumTrack
    dawIndex: 1
    rampSequencer: false
    chains:
      -
        name: Snares
        type: drum rack
        pads:
          - tblswvs.DS Snare
          - Snare DMX
          - Rim Glitcha
          - E-Perc BittyBot
      -
        name: Akoustic Dr Solo Rack
        type: drum rack
        pads:
          - slice 1
          - slice 2
          - slice 3
          - slice 4
          - slice 5
          - slice 6
          - slice 7
          - slice 8
          - slice 9
          - slice 10
          - slice 11
          - slice 12
          - slice 13
          - slice 14
          - slice 15
          - slice 16
  -
    name: Perc 1
    type: DrumTrack
    dawIndex: 2
    rampSequencer: false
    chains:
      -
        name: HiHat Rack
        type: drum rack
        pads:
          - HiHat 909 Closed
          - HiHat 909 Closed
          - HiHat 909 Closed
          - HiHat 909 Closed
          - HiHat 909 Closed
          - HiHat 909 Closed
          - HiHat 909 Closed
          - HiHat 909 Closed
          - HiHat Closed Bull Whip
          - HiHat Closed Click
          - HiHat Closed Crink
          - HiHat Closed Delay SP
          - HiHat Closed Loose Dirty
          - HiHat Closed Low Chop
          - HiHat Closed Metallic Char
          - HiHat Closed Modular Salient 1
      -
        name: Perc Rack
        type: drum rack
        pads:
          - Perc Glitch Speak
          - Perc Glitch Speak
          - Perc Glitch Speak
          - Perc Glitch Speak
          - Perc Abstract 5
          - Perc Abstract Token
          - Perc African MPC 1
          - Perc Alpha 3
          - Perc Analog Night
          - Perc Analog Token 1
          - Perc Broken Melt
          - Perc Broken Millimetrik
          - Perc Broken Tada
          - Perc Klang
          - Perc Digital Tada
          - Perc Dull Sonar
      -
        name: Meld Sample Pack Kit
        type: drum rack
        pads:
          - DS Kick
          - DS Snare
          - DS Hat
          - Mld Smpl Pck
  -
    name: Perc 2
    type: DrumTrack
    dawIndex: 3
    rampSequencer: false
    chains:
      -
        name: Chopped Breakin
        type: drum rack
        pads:
          - slice 1
          - slice 2
          - slice 3
          - slice 4
          - slice 5
          - slice 6
          - slice 7
          - slice 8
          - slice 9
          - slice 10
          - slice 11
          - slice 12
          - slice 13
          - slice 14
          - slice 15
          - slice 16
      -
        name: eptieda kit
        type: drum rack
        pads:
          - Sine Kick
          - Lw High Nz Snare
          - Sine Hat
          - Beep
          - Tom 1
          - Tom 2
          - Noise Click
          - Noise Burst
          - Echo Ping
      -
        name: nd.rsh-note-echo-beats
        type: drum rack
        pads:
          - Kick
          - Snare
          - HiHat
          - Bass
      -
        name: Base Sounds 1
        type: drum rack
        pads:
          - Kick 909 2
          - Clap Wild Canvas
          - Rim 3k Sharp
          - Hihat Open Chop BIS
          - Analog Wavetable 090
          - Analog Wavetable 103
          - Analog Wavetable 119
          - Hihat Open Brim
          - Harmonic Impact
          - FatDomino Drums 05 73bpm
          - Perc ER Fenk Short
          - Pot Knock
          - Boom Butter
          - Chop MSX XTRA
          - Modular Clatter
          - FatDomino Drums 11
      -
        name: Atonal FM Percs
        type: drum rack
        pads:
          - Unstable Noise Bangs DS FM
          - Random Klangs Meld
  -
    name: Bass
    type: MelodicTrack
    dawIndex: 4
    rampSequencer: true
    chains:
      -
        name: King Dubby
        type: synth
      -
        name: Basic FM8
        type: synth
      -
        name: Acid Base
        type: synth
      -
        name: squAErs
        type: synth
      -
        name: Growl Bass
        type: synth
      -
        name: early late bass
        type: synth
      -
        name: Akoustique
        type: synth
      -
        name: Acid Land (SM)
        type: synth
  -
    name: Keys
    type: MelodicTrack
    dawIndex: 5
    rampSequencer: true
    chains:
      -
        name: Meld Dirty Keys 2
        type: synth
      -
        name: Toy Keys 1
        type: synth
      -
        name: Toy Res Keys
        type: synth
      -
        name: Full Circle Dub
        type: synth
      -
        name: Jun-6 Piano 2
        type: synth
      -
        name: Glitch Dub
        type: synth
      -
        name: Dirty Bells
        type: synth
      -
        name: FM Mate
        type: synth
  -
    name: Pad
    type: MelodicTrack
    dawIndex: 6
    rampSequencer: true
    chains:
      -
        name: Mindbender
        type: synth
      -
        name: Jun-6 Jun's Vision
        type: synth
      -
        name: Metaz
        type: synth
      -
        name: Jeli Stutter Pad
        type: synth
      -
        name: Horn
        type: synth
      -
        name: Meymura Pad
        type: synth
      -
        name: eptieda pad
        type: synth
      -
        name: alandrandian
        type: synth
  -
    name: Hydra
    type: MelodicTrack
    dawIndex: 7
    rampSequencer: true
    chains:
      -
        name: Hydrasynth
        type: hardware
