live_tracks:
  -
    name: Kick
    type: MelodicTrack
    dawIndex: 1
    rampSequencer: false
    chains:
      -
        name: Kick Soft
        type: drumsampler
      -
        name: Kick Flared Out
        type: drumsampler
  -
    name: Snare
    type: MelodicTrack
    dawIndex: 2
    rampSequencer: false
    chains:
      -
        name: DS Snare
        type: synth
      -
        name: Snare DMX
        type: drumsampler
      -
        name: Rim Glitcha
        type: drumsampler
      -
        name: E-Perc BittyBot / Vinyl Click
        type: sampler
      -
        name: sm.atnl-fm-perc / sm.randres-pings
        type: synth
  -
    name: Perc 1
    type: DrumTrack
    dawIndex: 3
    rampSequencer: false
    chains:
      -
        name: HiHat Rack
        type: drum rack
        pads:
          - HiHat 909 Closed
          - HiHat 909 Closed
          - HiHat 909 Closed
          - HiHat 909 Closed
          - HiHat 909 Closed
          - HiHat 909 Closed
          - HiHat 909 Closed
          - HiHat 909 Closed
          - HiHat Closed Bull Whip
          - HiHat Closed Click
          - HiHat Closed Crink
          - HiHat Closed Delay SP
          - HiHat Closed Loose Dirty
          - HiHat Closed Low Chop
          - HiHat Closed Metallic Char
          - HiHat Closed Modular Salient 1
      -
        name: Perc Rack
        type: drum rack
        pads:
          - Perc Glitch Speak
          - Perc Glitch Speak
          - Perc Glitch Speak
          - Perc Glitch Speak
          - Perc Abstract 5
          - Perc Abstract Token
          - Perc African MPC 1
          - Perc Alpha 3
          - Perc Analog Night
          - Perc Analog Token 1
          - Perc Broken Melt
          - Perc Broken Millimetrik
          - Perc Broken Tada
          - Perc Klang
          - Perc Digital Tada
          - Perc Dull Sonar
      -
        name: Akoustic Dr Solo Rack
        type: drum rack
        pads:
          - slice 1
          - slice 2
          - slice 3
          - slice 4
          - slice 5
          - slice 6
          - slice 7
          - slice 8
          - slice 9
          - slice 10
          - slice 11
          - slice 12
          - slice 13
          - slice 14
          - slice 15
          - slice 16
      -
        name: Meld Sample Pack Kit
        type: drum rack
        pads:
          - DS Kick
          - DS Snare
          - DS Hat
          - Mld Smpl Pck
  -
    name: Perc 2
    type: DrumTrack
    dawIndex: 4
    rampSequencer: false
    chains:
      -
        name: Chopped Breakin
        type: drum rack
        pads:
          - slice 1
          - slice 2
          - slice 3
          - slice 4
          - slice 5
          - slice 6
          - slice 7
          - slice 8
          - slice 9
          - slice 10
          - slice 11
          - slice 12
          - slice 13
          - slice 14
          - slice 15
          - slice 16
      -
        name: eptieda kit
        type: drum rack
        pads:
          - Sine Kick
          - Lw High Nz Snare
          - Sine Hat
          - Beep
          - Tom 1
          - Tom 2
          - Noise Click
          - Noise Burst
          - Echo Ping
      -
        name: nd.rsh-note-echo-beats
        type: drum rack
        pads:
          - Kick
          - Snare
          - HiHat
          - Bass
      -
        name: Base Sounds 1
        type: drum rack
        pads:
          - Kick 909 2
          - Clap Wild Canvas
          - Rim 3k Sharp
          - Hihat Open Chop BIS
          - Analog Wavetable 090
          - Analog Wavetable 103
          - Analog Wavetable 119
          - Hihat Open Brim
          - Harmonic Impact
          - FatDomino Drums 05 73bpm
          - Perc ER Fenk Short
          - Pot Knock
          - Boom Butter
          - Chop MSX XTRA
          - Modular Clatter
          - FatDomino Drums 11
      -
        name: Atonal FM Percs
        type: drum rack
        pads:
          - Unstable Noise Bangs DS FM
          - Random Klangs Meld
  -
    name: Bass
    type: MelodicTrack
    dawIndex: 5
    rampSequencer: true
    chains:
      -
        name: King Dubby
        type: synth
      -
        name: Basic FM8
        type: synth
      -
        name: Acid Base
        type: synth
      -
        name: squAErs
        type: synth
      -
        name: early late bass
        type: synth
      -
        name: Akoustique
        type: synth
      -
        name: Acid Land (SM)
        type: synth
  -
    name: Keys
    type: MelodicTrack
    dawIndex: 6
    rampSequencer: true
    chains:
      -
        name: Meld Dirty Keys 2
        type: synth
      -
        name: Full Circle Dub
        type: synth
      -
        name: Jun-6 Piano 2
        type: synth
      -
        name: Glitch Dub
        type: synth
      -
        name: Dirty Bells
        type: synth
      -
        name: FM Mate
        type: synth
  -
    name: Pad
    type: MelodicTrack
    dawIndex: 7
    rampSequencer: true
    chains:
      -
        name: Mindbender
        type: synth
      -
        name: Jun-6 Jun's Vision
        type: synth
      -
        name: Metaz
        type: synth
      -
        name: eptieda pad
        type: synth
      -
        name: Meymura Pad
        type: synth
  -
    name: Hydra
    type: MelodicTrack
    dawIndex: 8
    rampSequencer: true
    chains:
      -
        name: Hydrasynth
        type: hardware
