live_tracks:
  -
    name: Kick
    dawIndex: 1
  -
    name: Snare
    dawIndex: 2
  -
    name: HiHat
    dawIndex: 3
  -
    name: Perc
    dawIndex: 4
    chains:
      -
        name: Resonator Perc
      -
        name: Kick & Perc Chokes
      -
        name: FM Four Pluck
  -
    name: Opsix
    dawIndex: 5
    chains:
      -
        name: A/B Pad
      -
        name: Basic FM
      -
        name: Simple Bass
      -
        name: OSC Juno
  -
    name: Hydra
    dawIndex: 6
    chains:
      -
        name: Hydrasynth
      -
        name: Glacial Tolerance
