live_tracks:
  -
    name: Kick
    dawIndex: 1
  -
    name: Snare
    dawIndex: 2
  -
    name: HiHat
    dawIndex: 3
  -
    name: Perc
    dawIndex: 4
  -
    name: Opsix
    dawIndex: 5
    chains:
      -
        name: A/B Pad (opsix native)
      -
        name: Basic FM (opsix native)
      -
        name: Simple Bass (opsix native)
  -
    name: Hydra
    dawIndex: 6
