live_tracks:
  -
    name: Kick
    dawIndex: 1
    chains:
      -
        name: Kick Flared Out
      -
        name: Kick Synth Melt
  -
    name: Snare
    dawIndex: 2
    chains:
      -
        name: Snare DMX
      -
        name: Safari Slaps 3
      -
        name: Clap 808
  -
    name: HiHat
    dawIndex: 3
    chains:
      -
        name: Hihat 909 Closed
      -
        name: Hihat Open Tokyo 1 Distorted
  -
    name: Perc
    dawIndex: 4
    chains:
      -
        name: E-Perc BittyBot
      -
        name: Reverb Kick & Perc Choked Kit
  -
    name: Bass
    dawIndex: 5
    chains:
      -
        name: Simple Bass
      -
        name: cnstrct.acid-bass
      -
        name: cnstrct.reese-bass
      -
        name: cnstrct.synth-bass
      -
        name: FM Four Pluck
  -
    name: Keys
    dawIndex: 6
    chains:
      -
        name: A/B Pad
      -
        name: FM Depth/Reverb Mod
      -
        name: OSC Juno
      -
        name: Glacial Tolerance
      -
        name: Sad Broken Drift
      -
        name: Basic FM
  -
    name: Hydra
    dawIndex: 7
